### ISSUE TITLE
dRegion - EssentialsX death message compatibility

### ISSUE THREAD

**Issue by Noiknez** [AnthonyAMC/Public-Denizen-Scripts#69]
Hi with the file DRegion_V2 i saw that death messages (essentialsx) is transforming into "cancelled" in white, but without the Dregion script i see death message normaly on my server. I see also the "cancelled" message when i deactivate the death message in essentials.
[http://prnt.sc/c66h1t](url)
I can link my configuration or more if you need it

**Comment by mcmonkey4eva** [comment]
It sounds like you're on an old version. Consider updating to 1.10 latest dev builds. Specifically the mineco dev build of Denizen, not Citizens or Spigot or Bukkit releases of Denizen.

**Comment by Noiknez** [comment]
Same problem when using the latest denizen dev build from jenkins

> [22:46:14] [INFO] cancelled

**Comment by AnthonyAMC** [comment]
I tested this a little bit and was able to reproduce the issue without EssentialsX. The issue was in the keep-items flag... the logic in that event is a bit inverted and as a result the flag processor was treating it as a cancelled death event... which you can't do, so it ended up changing the death message to 'cancelled'
Thanks for bringing it to my attention and here comes a fix.
